export const QUANTITY_MAX_COUNTERS = 20;
export const QUANTITY_MIN_VALUE_COUNTER = 0;
export const QUANTITY_MAX_VALUE_COUNTER = 20;
export const QUANTITY_MAX_CHARACTERS = 20;
export const QUANTITY_MIN_CHARACTERS = 0;
